Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,7 +37,7 @@ jobs:
       - name: Fix git permissions # multiple times i had an error just because i forgot to add this
         run: sudo chown -R $USER:$USER ${{ github.workspace }}
 
-      - name: Commit and push .SRCINFO and PKGBUILD if changed
+      - name: Commit and push .SRCINFO and PKGBUILD if changed # im not joking i ran this 3 times and i got an error because i specified the wrong github repo. so help me god...
         run: |
           cd ${{ github.workspace }}
           git config user.name "github-actions[bot]"
@@ -45,7 +45,7 @@ jobs:
           git add -u
           if ! git diff --cached --quiet; then
             git commit -m "GitHub Actions: Update .SRCINFO and PKGBUILD"
-            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/sparkhere-sys/arch.git HEAD || { echo "Push failed."; exit 255; }
+            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/sparkhere-sys/archapt.git HEAD || { echo "Push failed."; exit 255; }
           else
             echo "No changes in .SRCINFO, not commiting."
           fi
